### ISSUE TITLE
请问你提供的预训练模型是中文预训练模型 还是英文 是基于什么进行训练的 细节可以稍微介绍下吗

### ISSUE THREAD

**Issue by 652994331** [yitu-opensource/ConvBert#12]
我从readme 里下载了你的预训练模型 convbert_base convbert_medium convbert_small. 这三个模型 文件夹里没有词表， 我根据你项目中的词表 vocab.txt (30522维度) 我理解你这是英文的预训练模型，请问我理解的对吗(我是根据electra 来看 英文模型词表是30522 中文预训练模型 词表是 21128)。谢谢回答

**Comment by zihangJiang** [comment]
您好，是英文的预训练模型，在[OpenWebText](https://skylion007.github.io/OpenWebTextCorpus/)数据集上预训练。具体细节可以参考我们的[paper](https://arxiv.org/abs/2008.02496).
