### ISSUE TITLE
Training on multiple GPUs for BASE or LARGE Models

### ISSUE THREAD

**Issue by PhilipMay** [yitu-opensource/ConvBert#18]
Hi,

here https://github.com/yitu-opensource/ConvBert/issues/16#issuecomment-814256177 you say

> Our code is only tested on a single V100 GPU.

But in [your Paper](https://arxiv.org/abs/2008.02496) you write about BASE size ConvBERT models.

But BASE size models can not be trained (created) on a single GPU. From my experince you need 8 GPUs.

Could you please explain this? I would like to create a german BASE or maybe even LARGE new language model.

At https://github.com/yitu-opensource/ConvBert/issues/16#issuecomment-814256177 you say that Hugging Face might be an option for multi GPU training. From my experience they are good at downstream task training but not good at the initial language model creation.

I would be super happy about some help to create my new ConvBERT BASE or larger model in different languages.

Many thanks
Philip

**Comment by zihangJiang** [comment]
Hi Philip,

Thanks for your interest, the ConvBERT base model is trained on a TPU v3-8 (which has 8 cores). Our code is based on TensorFlow 1.x and the current codebase does not support multi GPU training. You'd better use TPU for training large models if you use this codebase.

**Comment by PhilipMay** [comment]
Ok. Thanks @zihangJiang !

Closing this again.
