### ISSUE TITLE
预测性能

### ISSUE THREAD

**Issue by colourful-tree** [yitu-opensource/ConvBert#5]
hi,
   请问有预测性能数据吗？
   比如, bert_base, bert_tiny, conv_bert, conv_bert_small

**Comment by zihangJiang** [comment]
Hi, please refer to Table 3 in [our paper](https://arxiv.org/pdf/2008.02496.pdf).

**Comment by colourful-tree** [comment]
![image](https://user-images.githubusercontent.com/17588577/99359451-0c5fdf00-28ea-11eb-81fa-e6c917338f9f.png)
这里是训练的指标吧？看起来数值是受【蒸馏Teacher模型】【训练数据量级】以及【网络反向传播】影响的。
请问有没有模型predict方面的实验数据

**Comment by zihangJiang** [comment]
If you mean inference speed, we have compared our mixed attention block with the traditional self-attention block in Table 9 (in Appendix).

**Comment by colourful-tree** [comment]
i see, thanks.
