### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by focox** [yitu-opensource/ConvBert#6]
![image](https://user-images.githubusercontent.com/30308731/99517286-253fc180-29ca-11eb-9619-9438605c9ec9.png)
论文描述中，这个部分是LConv，有点不解，望不吝解答，感谢

**Comment by zihangJiang** [comment]
您好，感谢您对我们项目的关注。
论文中的LConv的notation是为了更方便读者理解，实际implement我们参考了[pytorch/fairseq](https://github.com/pytorch/fairseq)中[lightconv的部分](https://github.com/pytorch/fairseq/blob/265791b727b664d4d7da3abd918a3f6fb70d7337/fairseq/modules/lightconv_layer/lightconv_layer.py#L75)和[dynamic conv的部分]( https://github.com/pytorch/fairseq/blob/265791b727b664d4d7da3abd918a3f6fb70d7337/fairseq/modules/dynamicconv_layer/dynamicconv_layer.py#L77)，我们code中的
https://github.com/yitu-opensource/ConvBert/blob/cc927862171a3b81bf2f8de5e3110a230d943d50/model/modeling.py#L969-L983
即为LConv的操作，与[pytorch/fairseq](https://github.com/pytorch/fairseq)中的实现是完全等价的。

如果您关于LConv还有其他问题，可以参考[Pay Less Attention with Lightweight and Dynamic Convolutions](https://openreview.net/pdf?id=SkVhlh09tX)和[pytorch/fairseq](https://github.com/pytorch/fairseq)，其中有更详细的解释和注释。

另外，希望您修改一下issue的标题，以免引起误解。
